// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Proto/Model.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Model {

  /// <summary>Holder for reflection information generated from Proto/Model.proto</summary>
  public static partial class ModelReflection {

    #region Descriptor
    /// <summary>File descriptor for Proto/Model.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ModelReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChFQcm90by9Nb2RlbC5wcm90bxIFbW9kZWwi4QEKBU1vZGVsEhIKCkxvbmdT",
            "dHJpbmcYASABKAkSEAoISW50QXJyYXkYAiADKAUSJQoKSW5uZXJNb2RlbBgD",
            "IAEoCzIRLm1vZGVsLklubmVyTW9kZWwSEwoLRG91YmxlVmFsdWUYBCABKAES",
            "EQoJTG9uZ1ZhbHVlGAUgASgDEjAKCkRpY3Rpb25hcnkYBiADKAsyHC5tb2Rl",
            "bC5Nb2RlbC5EaWN0aW9uYXJ5RW50cnkaMQoPRGljdGlvbmFyeUVudHJ5EgsK",
            "A2tleRgBIAEoCRINCgV2YWx1ZRgCIAEoCToCOAEiSAoKSW5uZXJNb2RlbBIT",
            "CgtJbm5lclN0cmluZxgBIAEoCRIQCghJbm5lckludBgCIAEoBRITCgtJbm5l",
            "ckRvdWJsZRgDIAEoAWIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Model.Model), global::Model.Model.Parser, new[]{ "LongString", "IntArray", "InnerModel", "DoubleValue", "LongValue", "Dictionary" }, null, null, null, new pbr::GeneratedClrTypeInfo[] { null, }),
            new pbr::GeneratedClrTypeInfo(typeof(global::Model.InnerModel), global::Model.InnerModel.Parser, new[]{ "InnerString", "InnerInt", "InnerDouble" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class Model : pb::IMessage<Model>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Model> _parser = new pb::MessageParser<Model>(() => new Model());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Model> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Model.ModelReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Model() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Model(Model other) : this() {
      longString_ = other.longString_;
      intArray_ = other.intArray_.Clone();
      innerModel_ = other.innerModel_ != null ? other.innerModel_.Clone() : null;
      doubleValue_ = other.doubleValue_;
      longValue_ = other.longValue_;
      dictionary_ = other.dictionary_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Model Clone() {
      return new Model(this);
    }

    /// <summary>Field number for the "LongString" field.</summary>
    public const int LongStringFieldNumber = 1;
    private string longString_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string LongString {
      get { return longString_; }
      set {
        longString_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "IntArray" field.</summary>
    public const int IntArrayFieldNumber = 2;
    private static readonly pb::FieldCodec<int> _repeated_intArray_codec
        = pb::FieldCodec.ForInt32(18);
    private readonly pbc::RepeatedField<int> intArray_ = new pbc::RepeatedField<int>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<int> IntArray {
      get { return intArray_; }
    }

    /// <summary>Field number for the "InnerModel" field.</summary>
    public const int InnerModelFieldNumber = 3;
    private global::Model.InnerModel innerModel_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Model.InnerModel InnerModel {
      get { return innerModel_; }
      set {
        innerModel_ = value;
      }
    }

    /// <summary>Field number for the "DoubleValue" field.</summary>
    public const int DoubleValueFieldNumber = 4;
    private double doubleValue_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public double DoubleValue {
      get { return doubleValue_; }
      set {
        doubleValue_ = value;
      }
    }

    /// <summary>Field number for the "LongValue" field.</summary>
    public const int LongValueFieldNumber = 5;
    private long longValue_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long LongValue {
      get { return longValue_; }
      set {
        longValue_ = value;
      }
    }

    /// <summary>Field number for the "Dictionary" field.</summary>
    public const int DictionaryFieldNumber = 6;
    private static readonly pbc::MapField<string, string>.Codec _map_dictionary_codec
        = new pbc::MapField<string, string>.Codec(pb::FieldCodec.ForString(10, ""), pb::FieldCodec.ForString(18, ""), 50);
    private readonly pbc::MapField<string, string> dictionary_ = new pbc::MapField<string, string>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::MapField<string, string> Dictionary {
      get { return dictionary_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Model);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Model other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (LongString != other.LongString) return false;
      if(!intArray_.Equals(other.intArray_)) return false;
      if (!object.Equals(InnerModel, other.InnerModel)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(DoubleValue, other.DoubleValue)) return false;
      if (LongValue != other.LongValue) return false;
      if (!Dictionary.Equals(other.Dictionary)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (LongString.Length != 0) hash ^= LongString.GetHashCode();
      hash ^= intArray_.GetHashCode();
      if (innerModel_ != null) hash ^= InnerModel.GetHashCode();
      if (DoubleValue != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(DoubleValue);
      if (LongValue != 0L) hash ^= LongValue.GetHashCode();
      hash ^= Dictionary.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (LongString.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(LongString);
      }
      intArray_.WriteTo(output, _repeated_intArray_codec);
      if (innerModel_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(InnerModel);
      }
      if (DoubleValue != 0D) {
        output.WriteRawTag(33);
        output.WriteDouble(DoubleValue);
      }
      if (LongValue != 0L) {
        output.WriteRawTag(40);
        output.WriteInt64(LongValue);
      }
      dictionary_.WriteTo(output, _map_dictionary_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (LongString.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(LongString);
      }
      intArray_.WriteTo(ref output, _repeated_intArray_codec);
      if (innerModel_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(InnerModel);
      }
      if (DoubleValue != 0D) {
        output.WriteRawTag(33);
        output.WriteDouble(DoubleValue);
      }
      if (LongValue != 0L) {
        output.WriteRawTag(40);
        output.WriteInt64(LongValue);
      }
      dictionary_.WriteTo(ref output, _map_dictionary_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (LongString.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(LongString);
      }
      size += intArray_.CalculateSize(_repeated_intArray_codec);
      if (innerModel_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(InnerModel);
      }
      if (DoubleValue != 0D) {
        size += 1 + 8;
      }
      if (LongValue != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(LongValue);
      }
      size += dictionary_.CalculateSize(_map_dictionary_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Model other) {
      if (other == null) {
        return;
      }
      if (other.LongString.Length != 0) {
        LongString = other.LongString;
      }
      intArray_.Add(other.intArray_);
      if (other.innerModel_ != null) {
        if (innerModel_ == null) {
          InnerModel = new global::Model.InnerModel();
        }
        InnerModel.MergeFrom(other.InnerModel);
      }
      if (other.DoubleValue != 0D) {
        DoubleValue = other.DoubleValue;
      }
      if (other.LongValue != 0L) {
        LongValue = other.LongValue;
      }
      dictionary_.MergeFrom(other.dictionary_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            LongString = input.ReadString();
            break;
          }
          case 18:
          case 16: {
            intArray_.AddEntriesFrom(input, _repeated_intArray_codec);
            break;
          }
          case 26: {
            if (innerModel_ == null) {
              InnerModel = new global::Model.InnerModel();
            }
            input.ReadMessage(InnerModel);
            break;
          }
          case 33: {
            DoubleValue = input.ReadDouble();
            break;
          }
          case 40: {
            LongValue = input.ReadInt64();
            break;
          }
          case 50: {
            dictionary_.AddEntriesFrom(input, _map_dictionary_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            LongString = input.ReadString();
            break;
          }
          case 18:
          case 16: {
            intArray_.AddEntriesFrom(ref input, _repeated_intArray_codec);
            break;
          }
          case 26: {
            if (innerModel_ == null) {
              InnerModel = new global::Model.InnerModel();
            }
            input.ReadMessage(InnerModel);
            break;
          }
          case 33: {
            DoubleValue = input.ReadDouble();
            break;
          }
          case 40: {
            LongValue = input.ReadInt64();
            break;
          }
          case 50: {
            dictionary_.AddEntriesFrom(ref input, _map_dictionary_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class InnerModel : pb::IMessage<InnerModel>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<InnerModel> _parser = new pb::MessageParser<InnerModel>(() => new InnerModel());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<InnerModel> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Model.ModelReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public InnerModel() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public InnerModel(InnerModel other) : this() {
      innerString_ = other.innerString_;
      innerInt_ = other.innerInt_;
      innerDouble_ = other.innerDouble_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public InnerModel Clone() {
      return new InnerModel(this);
    }

    /// <summary>Field number for the "InnerString" field.</summary>
    public const int InnerStringFieldNumber = 1;
    private string innerString_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string InnerString {
      get { return innerString_; }
      set {
        innerString_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "InnerInt" field.</summary>
    public const int InnerIntFieldNumber = 2;
    private int innerInt_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int InnerInt {
      get { return innerInt_; }
      set {
        innerInt_ = value;
      }
    }

    /// <summary>Field number for the "InnerDouble" field.</summary>
    public const int InnerDoubleFieldNumber = 3;
    private double innerDouble_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public double InnerDouble {
      get { return innerDouble_; }
      set {
        innerDouble_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as InnerModel);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(InnerModel other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (InnerString != other.InnerString) return false;
      if (InnerInt != other.InnerInt) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(InnerDouble, other.InnerDouble)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (InnerString.Length != 0) hash ^= InnerString.GetHashCode();
      if (InnerInt != 0) hash ^= InnerInt.GetHashCode();
      if (InnerDouble != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(InnerDouble);
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (InnerString.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(InnerString);
      }
      if (InnerInt != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(InnerInt);
      }
      if (InnerDouble != 0D) {
        output.WriteRawTag(25);
        output.WriteDouble(InnerDouble);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (InnerString.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(InnerString);
      }
      if (InnerInt != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(InnerInt);
      }
      if (InnerDouble != 0D) {
        output.WriteRawTag(25);
        output.WriteDouble(InnerDouble);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (InnerString.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(InnerString);
      }
      if (InnerInt != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(InnerInt);
      }
      if (InnerDouble != 0D) {
        size += 1 + 8;
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(InnerModel other) {
      if (other == null) {
        return;
      }
      if (other.InnerString.Length != 0) {
        InnerString = other.InnerString;
      }
      if (other.InnerInt != 0) {
        InnerInt = other.InnerInt;
      }
      if (other.InnerDouble != 0D) {
        InnerDouble = other.InnerDouble;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            InnerString = input.ReadString();
            break;
          }
          case 16: {
            InnerInt = input.ReadInt32();
            break;
          }
          case 25: {
            InnerDouble = input.ReadDouble();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            InnerString = input.ReadString();
            break;
          }
          case 16: {
            InnerInt = input.ReadInt32();
            break;
          }
          case 25: {
            InnerDouble = input.ReadDouble();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
